### ISSUE TITLE
when i run node server.js 1234 password it wont work

### ISSUE THREAD

**Issue by ghost** [unixpickle/hashcrack#1]
when i run node server.js 1234 password it says node command not found 
so then i tried nodejs server.js 1234 password and this happens
$ nodejs server.js 1234 password

module.js:340
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/fred2104/work/src/github.com/unixpickle/hashcrack/server.js:7:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by unixpickle** [comment]
You need to use npm to install the dependencies. Try `npm install` before running the actual server.

**Comment by ghost** [comment]
ok

**Comment by ghost** [comment]
thanks that worked
